image: dchevell/docker-release-maker:latest
clone:
  depth: full

pipelines:
  custom:
    create-release:
      - step:
          script:
            - git fetch --all
            - export BASE_BRANCH=base-7
            - export BASE_VERSION=7
            - export DOCKER_REPO=dchevell/jira-software
            - export DOCKERFILE_VERSION_STRING=JIRA_VERSION
            - export GIT_USER=bambooagent
            - export GIT_EMAIL=build-agent@atlassian.com
            - export MAC_PRODUCT_KEY=jira-software
            - python /usr/src/app/create_release.py
  branches:
    base-7:
      - step:
          script:
            - git fetch --all
            - export BASE_BRANCH=base-7
            - export BASE_VERSION=7
            - export DOCKER_REPO=dchevell/jira-software
            - export DOCKERFILE_VERSION_STRING=JIRA_VERSION
            - export GIT_USER=bambooagent
            - export GIT_EMAIL=build-agent@atlassian.com
            - export MAC_PRODUCT_KEY=jira-software
            - python /usr/src/app/update_release.py